---
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"
  - echo "localhost" > inventory

script:
  - ansible-playbook docker-traefik.yml -i inventory --syntax-check
  - ansible-playbook docker-traefik.yml -i inventory | grep -q 'changed=0.*failed=0 && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
