language: minimal
services: docker

before_script:

  - docker pull buildpack-deps:artful-curl
  - shopt -s expand_aliases
  - alias curl='docker run --rm --net=host buildpack-deps:artful-curl curl'

script:
  - docker swarm init
  - docker network create traefik-net --driver overlay
  - docker stack deploy -c ./files/docker-compose.yml proxy
  - sleep 60
  - docker stack services proxy
  - docker service create --name whoami0 --label traefik.port=80 --network traefik-net emilevauge/whoami
  - sleep 5
  - curl -H 'Host: whoami0.traefik' -s --retry 10 --retry-delay 5 --retry-connrefused -D- http://localhost/
