sudo: required

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  #- docker pull tutum/curl:alpine
  #- shopt -s expand_aliases
  #- alias curl='docker run --rm --net=host tutum/curl:alpine curl'

script:
  - docker --version
  - docker swarm init
  - docker network create traefik-net --driver overlay
  - docker stack deploy -c ./files/docker-compose.yml proxy
  - sleep 60
  - docker stack services proxy
  - docker service create --name whoami0 --label traefik.port=80 --network traefik-net emilevauge/whoami
  - sleep 5
  - curl -H 'Host: whoami0.traefik' -s --retry 10 --retry-delay 5 --retry-connrefused -D- http://localhost/
