sudo: required

#services:
#  - docker

#before_install:
#  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
#  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
#  - sudo apt-get update
#  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

#script:
#  - docker --version
#  - docker swarm init
#  - docker network create traefik-net --driver overlay
#  - docker stack deploy -c ./files/docker-compose.yml proxy
#  - sleep 10
#  - docker stack services proxy
#  - docker service create --name whoami0 --label traefik.port=80 --network traefik-net emilevauge/whoami
#  - sleep 5
#  - curl --fail -H Host:whoami0.traefik http://localhost/
  
#sudo: required
dist: trusty

language: python
python: "2.7"

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo apt-get install python-apt -y
  - echo "localhost" > inventory
  - sed -i 's/\ all/\ all\n\ \ connection:\ local\n\ \ become:\ yes/' docker-traefik.yml

install:
  - pip install git+git://github.com/ansible/ansible.git@devel --upgrade
  - pip install ansible-lint
  - pip show ansible

script:
  - docker swarm init
  - docker node list
  - docker service ls
  - ansible-playbook docker-traefik-devel.yml -i inventory --syntax-check
  - ansible-playbook docker-traefik-devel.yml -i inventory
  - sleep 5
  - docker service create --name whoami0 --label traefik.port=80 --network traefik-net emilevauge/whoami
  - sleep 5
  - curl --fail -H Host:whoami0.traefik http://localhost/
