- name: run reverse-proxy docker 
  hosts:  all 
  tasks:
   - name: install pip
     apt: name=python-pip state=present

   - name: install docker py
     pip: name=docker state=present version=2.6

   - name: create a network
     docker_network:
       name: traefik-net
       driver: overlay 

   - name: copy compose file
     copy: src=docker-compose.yml dest=/opt/docker-compose-traefik.yml

   - name: run stack traefik 
     docker_stack:
       state: present
       name: proxy 
       compose:
        - /opt/docker-compose-traefik.yml
